version: "3.8"

services:
  nest-api:
    image: 'node-talks/api:latest'
    container_name: nest-api
    depends_on: 
      - postgres-db
    links:
      - postgres-db:postgres-db
    ports:
      - 3000:3000
    networks:
      - node-talks-network
    restart: on-failure
    environment: 
      PROJECT_ENV: local
      DB_TYPE: 
      DB_HOST: 
      DB_PORT: 
      DB_USERNAME: 
      DB_PASSWORD: 
      DB_DATABASE: 
      OAUTH_CLIENT_ID: 
      OAUTH_CLIENT_SECRET: 
      OAUTH_CALLBACK_URL: 
  postgres-db:
    container_name: postgresql-api
    image: postgres:14-alpine
    restart: always
    environment: 
      POSTGRES_HOST_AUTH_METHOD: trust
      POSTGRES_USER: 
      POSTGRES_PASSWORD: 
      POSTGRES_DB: 
    volumes:
      - ./postgres-data:/var/lib/postgresql/data
    ports:
      - 5432:5432
    expose:
      - 5432
    networks:
      - node-talks-network
networks:
    node-talks-network: